


/usr/local/src/prg/xc/doc/sphinxDoc/source/preprocessor/cpp_classes/preprocessor/set_mgmt/set_mgmt.rst:62: WARNING: autodoc: failed to import class u'lst_ptr_cu

/usr/local/src/prg/xc/doc/sphinxDoc/source/preprocessor/python_modules/actions.railway_trafic.rst:24: WARNING: autodoc: failed to import module u'actions.railway_trafic.vientoIAPF'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
ImportError: No module named vientoIAPF
/usr/local/src/prg/xc/doc/sphinxDoc/source/preprocessor/python_modules/actions.wind.rst:8: WARNING: autodoc: failed to import module u'actions.wind.vientoCTE'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
ImportError: No module named vientoCTE
/usr/local/src/prg/xc/doc/sphinxDoc/source/preprocessor/python_modules/actions.wind.rst:16: WARNING: autodoc: failed to import module u'actions.wind.vientoCubiertaDosAguasCTE'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
ImportError: No module named vientoCubiertaDosAguasCTE
/usr/local/src/prg/xc/doc/sphinxDoc/source/preprocessor/python_modules/actions.wind.rst:24: WARNING: autodoc: failed to import module u'actions.wind.vientoCubiertaPlanaCTE'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
ImportError: No module named vientoCubiertaPlanaCTE
/usr/local/src/prg/xc/doc/sphinxDoc/source/preprocessor/python_modules/actions.wind.rst:32: WARNING: autodoc: failed to import module u'actions.wind.vientoMarquesinaCTE'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
ImportError: No module named vientoMarquesinaCTE
/usr/local/src/prg/xc/doc/sphinxDoc/source/preprocessor/python_modules/actions.wind.rst:40: WARNING: autodoc: failed to import module u'actions.wind.vientoParamVerticalesCTE'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
ImportError: No module named vientoParamVerticalesCTE
/usr/local/src/prg/xc/doc/sphinxDoc/source/solution/cpp_classes/analysis/analysis/analysis_types.rst:42: WARNING: autodoc: failed to import class u'DomainDecompositionAnalysis' from module u'xc'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 393, in import_object
    obj = self.get_attr(obj, part)
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 289, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python2.7/dist-packages/sphinx/util/inspect.py", line 115, in safe_getattr
    raise AttributeError(name)
AttributeError: DomainDecompositionAnalysis

/usr/local/src/prg/xc/doc/sphinxDoc/source/solution/cpp_classes/analysis/analysis/analysis_types.rst:46: WARNING: autodoc: failed to import class u'StaticDomainDecompositionAnalysis' from module u'xc'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 393, in import_object
    obj = self.get_attr(obj, part)
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 289, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python2.7/dist-packages/sphinx/util/inspect.py", line 115, in safe_getattr
    raise AttributeError(name)
AttributeError: StaticDomainDecompositionAnalysis
/usr/local/src/prg/xc/doc/sphinxDoc/source/solution/cpp_classes/analysis/analysis/analysis_types.rst:50: WARNING: autodoc: failed to import class u'TransientDomainDecompositionAnalysis' from module u'xc'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 393, in import_object
    obj = self.get_attr(obj, part)
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 289, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python2.7/dist-packages/sphinx/util/inspect.py", line 115, in safe_getattr
    raise AttributeError(name)
AttributeError: TransientDomainDecompositionAnalysis
/usr/local/src/prg/xc/doc/sphinxDoc/source/solution/cpp_classes/analysis/numberer/numberer.rst:6: WARNING: autodoc: failed to import class u'DOF_Numberer' from module u'xc'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 393, in import_object
    obj = self.get_attr(obj, part)
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 289, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python2.7/dist-packages/sphinx/util/inspect.py", line 115, in safe_getattr
    raise AttributeError(name)
AttributeError: DOF_Numberer
/usr/local/src/prg/xc/doc/sphinxDoc/source/preprocessor/cpp_classes/domain/mesh/element/special/frictionBearing/frictionBearing.rst:: WARNING: document isn't included in any toctree
/usr/local/src/prg/xc/doc/sphinxDoc/source/preprocessor/cpp_classes/domain/mesh/element/special/frictionBearing/frictionModel/frictionModel.rst:: WARNING: document isn't included in any toctree
/usr/local/src/prg/xc/doc/sphinxDoc/source/solution/cpp_classes/system_of_eqn/linearSOE/linearSOE.rst:: WARNING: document isn't included in any toctree
